### PR TITLE
(Optionally) auto-disable other overlays for a target package when enabling a new one

### PR DESCRIPTION
**Pull request by boswelja**
Tested and appears to be working fine :D

### CODE REVIEW

**Comment by boswelja** [comment]
Resolves #125

**Comment by boswelja** [comment]
Also disabling is enforced in legacy mode as you can only install one overlay per app at a time anyways

**Comment by boswelja** [comment]
pardon all the stuff in the middle, couldn't get git to merge without the "Merged branch dev of substratum" commit

**Comment by msfjarvis** [comment]
Can you create a new branch on your fork, hard reset it to substratum:dev and add your changes on top? I'd prefer it be that way. I'm eager to get this into dev and start having it tested :)

**Comment by boswelja** [comment]
@MSF-Jarvis Sure, just waiting on Android Studio to finish updating, then I'll clean it all up

**Comment by boswelja** [comment]
OK, I'm gonna close this and open a new PR soon

**Comment by msfjarvis** [comment]
@boswelja Thanks.

**Pull request closed without merging**
