### PR TITLE
ZipAlign APKs

### PR DESCRIPTION
**Pull request by arter97**
I'm **VERY** surprised to see that this is not done already.

Please merge this ASAP after code review.

### CODE REVIEW

**Comment by nicholaschum** [comment]
You raise a valid point where ZipAligned APKs streamline the performance of the system.

We were prioritizing speed of compilation prior to the commit, so have you felt any significant compilation delays or not being able to install on top of a previous (pre-816 overlay)?

I'm completely down for this commit. Thank you @arter97!

**Comment by arter97** [comment]
This will obviously slow down the compilation.
This operation is mostly dependent on I/O performance. Think of it as copying the APK once more for every overlays.

However, the benefit of aligning outweighs this drawback by a lot.
I've seen gigs of more memory usage if all APKs are misaligned, compared to normal.

And by the way, for better compilation speed, parallelization is the answer.
Maintainers of substratum should look into this :)

**Comment by arter97** [comment]
Ah, and since you asked, I didn't notice the worsened compilation speed.
Probably because my OP3's storage I/O is fast enough..

**Comment by nicholaschum** [comment]
Yup, I merged it to dev so that we can begin testing heavily!

Yeah it makes sense that it should have drawbacks, but I agree at this point, the outcome outweighs the current implementation.

We will be keeping this PR up to date with new findings if there are any, thanks again!

**Comment by arter97** [comment]
Thanks for merging this quickly.
I don't expect any issues, but yeah, we should test.

I'd change the version to 900 if I were you. This is a major improvement.
Just sayin' lol

**Comment by nicholaschum** [comment]
Hahaha! Yeah, people always criticized me for always changing to arbitrary numbers because I feel like it's a "huge change", which was why our previous major release was just a version number bump just to make them feel like they can't predict my numbering practices xD

**Comment by nicholaschum** [comment]
Alright, we have had some testers report back that compilation takes longer (some even a minute longer) on older devices. Also a few Pixel reports too strangely. I still like this implementation however the compilation time may throw off older devices or weaker devices. I would suggest adding a switch to disable this on older devices.

**Comment by arter97** [comment]
Uh, older devices need this more desperately.

How about implementing multi threaded compilation, while you're at it?

**Comment by nicholaschum** [comment]
@Surge1223 was going to look at changing up the current compilation task, he might be interested in doing that.

**Comment by artem** [comment]
@arter97 Isn't alignment lost after APK signing?

**Comment by arter97** [comment]
No.

https://developer.android.com/studio/command-line/zipalign.html

Substratum uses apksigner.

**Comment by nicholaschum** [comment]
Just to update. I have tested this on my hammerhead running latest PA and it runs perfectly, just as fast as before. So I decided we might not even need a toggle.

**Pull request merged**
