### PR TITLE
SubstratumUI : Turn on Nougat-Style cards by default

### PR DESCRIPTION
**Pull request by msfjarvis**
These just look so much better than the current default

### CODE REVIEW

**Comment by jakubschenk** [comment]
@MSF-Jarvis finally

**Comment by nicholaschum** [comment]
@MSF-Jarvis No

**Comment by hbashton** [comment]
@nicholaschum !id

**Comment by msfjarvis** [comment]
@nicholaschum Okay ;--;

**Comment by valiantshadow** [comment]
@nicholaschum ;(

**Comment by AOSiP-Gerrit** [comment]
@MSF-Jarvis Ikr

**Comment by akhilnarang** [comment]
@MSF-Jarvis Ikr

**Comment by AmolAmrit** [comment]
@nicholaschum please 😢😭

**Comment by out386** [comment]
@MSF-Jarvis, meh.

**Comment by hbashton** [comment]
@out386 Lel

**Comment by valiantshadow** [comment]
@MSF-Jarvis Substratum only has full functionality on N, we should merge this to keep things consistent.

**Comment by akhilnarang** [comment]
@out386 No u

**Comment by out386** [comment]
Looks cluttered without any dividers. A bit of top padding would go well, maybe?

**Pull request closed without merging**
