### PR TITLE
Add support for DU's ACCESS_SERVICE_INNER permission

### PR DESCRIPTION
**Pull request by andrzejressel**

### CODE REVIEW

**Comment by Sykopompos** [comment]
@jereksel Would be helpful to link du's inner permission commit so we would know what you are talking about

**Comment by andrzejressel** [comment]
@Sykopompos https://github.com/DirtyUnicorns/android_packages_services_ThemeInterfacer/commit/bf1194a736e38e40d19093e2fe63b14663bc180a

**Comment by Sykopompos** [comment]
@jereksel Why is this needed? This is only supposed to be for debugging and development purposes and not to be for general use to leave on.

It's just like usb-debugging is not meant to be on all the time because it circumvents security

**Comment by andrzejressel** [comment]
People must enable it to use your nightly builds - I'm not considering that debugging or developing anymore.

**Comment by Sykopompos** [comment]
@jereksel Ci builds are normally pushed to play store within a few days, the only time they are not is when there is active major development and things need to be tested.
They are not meant for regular usage.

If this is meant for your libreSubstratum, then as I suggested before setup the whitelist for it with interfacer and put the commit up on gerrit but going through something meant for debugging/development purposes for everyday use is a bad proposal

**Comment by nicholaschum** [comment]
I'd like to know more about your commit as well @jereksel.

Your commit message was rather poorly phrased, where you said "every application can get user's private data". Interfacer has been coded to **only** access theme related data folders specified by the sepolicy. Unless the sepolicy was modified heavily, Interfacer throws FNFEs, as I had a few users test.  If you have a live usage case, please do reply to this with a way to access "user's private data", like my bank app's SharedPreferences. At most, any application could leverage Interfacer to get and add to a user's theme data, in /data/system/theme, as specified by the sepolicy, which only controls bootanimations, fonts and sounds.

You must also have to take account for the apps who request that permission before Interfacer was upgraded using that commit, as apps which use a custom permission not properly defined (because it was only created in Interfacer) will no longer re-request an update to the permission once a dirty flash was initiated, so adding the permission will mean that people will have to uninstall all theme systems on their device causing bad transitioning. (e.g. if everyone was running on the build before your Interfacer commit and I added `projekt.interfacer.permission.ACCESS_SERVICE_INNER` to Substratum, then the users upgraded to the latest version of DU, Substratum will not use that permission because it was not understood by the system as being a dangerous permission.

Don't get me wrong but I do see the potential of the extra dialog, if you can push the commit to our Gerrit for review on our end, that would be highly appreciated.

**Pull request closed without merging**
