### PR TITLE
Rootless SystemUI restart

### PR DESCRIPTION
**Pull request by simonesestito**
Install a malformed overlay to crash SystemUI internally, restarting it without rebooting or rooting, clicking the "Restart SystemUI" options item in InformationActivity

NOTE: tested only on Android Oreo 8.0.0 - Nexus 5X

Special thanks to @A-Panic for the overlay itself

### CODE REVIEW

**Comment by nathanchance** [comment]
1. Unless I'm missing something, the actual overlay appears to be missing. 

2. The idea of intentionally crashing a core part of the UI is pretty horrible in my opinion. Especially with Rescue Party now being a thing.

**Comment by Sykopompos** [comment]
👍👍 nathan

**Comment by simonesestito** [comment]
1. Yes, the overlay doesn't appear in the overlays list because it isn't a user-installed overlay. Anyway, it's possible to show it by adding substratum's meta info in overlay manifest.

2. The crash is the only way to restart SystemUI without reboot (because it breaks Andromeda connection) and root. I've tested that all applied overlays to SystemUI still enabled after restarting

**Comment by msfjarvis** [comment]
@simonesestito Where is the "substratum.crasher" package, is what Nathan meant.

**Comment by nathanchance** [comment]
@simonesestito I meant it's not added in this pull, you reference it in the last commit but I don't see where it is generated or called from. 

I still don't like this, it's just bad UX.

**Comment by Sykopompos** [comment]
@nathanchance In before substratum wiped my data

**Comment by simonesestito** [comment]
@MSF-Jarvis it's in assets (4KB) and it'll be auto-installed at https://github.com/simonesestito/substratum/blob/9f6310ab1a4436efae9600358649ee2dc698711d/app/src/main/java/projekt/substratum/common/platform/AndromedaService.java#L106

**Comment by simonesestito** [comment]
I didn't write that the crash is used ONLY if:
- there's no root
- it's Oreo + Andromeda
- the user clicks on Restart SystemUI explicity. Reboot is a preferred option, but a user has the possibility to manully restart it

**Comment by simonesestito** [comment]
@nathanchance ops, I didn't see I haven't added it in the commit
It's because .gitignore all APKs

**Comment by nathanchance** [comment]
@simonesestito let me put it this way, if the user sees a force close dialog, I don't like this.

The rest of the team will weigh in on this before any action is taken but that's my personal opinion. Regardless of the outcome, thank you very much for the pull request!

**Comment by simonesestito** [comment]
@nathanchance ok!

For everybody and a better understanding, I'll leave an example:
you enable some overlays, included SystemUI. They will be applied as usual, but no crash happens at all.
now the user has 3 options: 1) restart systemui manually, 2) reboot, 3) do nothing
Only if user explicity goes to InformationActivity, clicks the options menu, then Restart SystemUI, it'll see a crash dialog. If user does nothing, installs other overlays, reboots, and so on, no crash dialog appear.

Said this, peace!

**Comment by ghost** [comment]
@nathanchance Send logs

**Comment by jojmaht** [comment]
@simonesestito But are we allowed to actually prepackage the apk, though? I thought the Play Store didn't allow that?

**Comment by simonesestito** [comment]
@skinnyfoetusboy I've asked to Google Play Policy team. Waiting for their reply

**Comment by nicholaschum** [comment]
We aren't able to prebuild an asset overlay to place on Google

**Comment by simonesestito** [comment]
As @nicholaschum and other my friends confirmed, unfortunately, adding an apk isn't allowed. But it's allowed to insert a decompiled zip and compile it in the app itself (nothing official from Google, just a past experience of this friend).

Anyway, thanks for your time. Only for myself I did an extremely simple app which talks to Andromeda backend and does what these commits do.

Peace, and see you next time!

**Pull request closed without merging**
