### PR TITLE
Dynamic TroubleshootFragment

### PR DESCRIPTION
**Pull request by codekidX**
- added commits to save some resources and add troubleshoot instructions via code itself. 
- added padding to total 16dp instead of 17dp w.r.t guidelines

### CODE REVIEW

**Comment by nicholaschum** [comment]
@codekidX Code Review: please could you do a reformat and import optimization with an 80 char wrapping limit, as well as TroubleShootingAdapter should be TroubleshootingAdapter without a capitalized S. Layout file should retain the name scheme of troubleshooting instead of just troubleshoot. Thanks!

**Comment by codekidX** [comment]
Ya sure, I guess habits don't die. I'll create a new pull request with changes specified.

**Comment by nicholaschum** [comment]
@codekidX No need for a new pull request, just gotta upload your changes to your branch and update the pull request.

**Comment by codekidX** [comment]
@nicholaschum I came to know just now 👶  ..Pushed commit the changes now. I'm messing bigtime today. See "convention" spelling lol.

**Review by nicholaschum — APPROVED** [review]

**Comment by nicholaschum** [comment]
@codekidX No problem! If you ever need to ever rename a future commit you can always "git commit --amend" and then force push to the previous parent commit branch so you can rename something. We call this rewriting history :)

**Comment by codekidX** [comment]
Alright I'll do that, I do not have much experience with Git. Can I clean up resources of TeamFragment the same way ?

**Comment by nicholaschum** [comment]
@codekidX Resources? The way I mentioned is pretty much just for commit history purposes. If you wanna make changes at this point (after PR merge) then you gotta recommit and create a new pull request.

**Comment by codekidX** [comment]
@nicholaschum Ok Thanks !

**Pull request merged**
