### PR TITLE
update

### PR DESCRIPTION
**Pull request by ivaniskandar**

### CODE REVIEW

**Comment by jakubschenk** [comment]
@iskandar1023 u suk ivan

**Comment by KreAch3R** [comment]
Wait, did we solve the problems with the refreshwindows call elsewhere? Otherwise this PR (as is) should break OMS3 fonts reset.

**Comment by nicholaschum** [comment]
@KreAch3R fixed.

**Comment by xdevs23** [comment]
@nicholaschum LOL

**Comment by xdevs23** [comment]
@xdevs23 Lol

**Comment by xdevs23** [comment]
@xdevs23 Ok sorry i'll stop now

**Pull request merged**
