### PR TITLE
Includes all bug fixes past, present, and future

### PR DESCRIPTION
**Pull request by codebam**
I just deleted the whole repo

### CODE REVIEW

**Comment by nathanchance** [comment]
lolwut

**Comment by khusika** [comment]
😂

**Comment by sokryptk** [comment]
@codebam @codebam

**Comment by msfjarvis** [comment]
Imma stick with bugz but 10/10 for effort

**Comment by akhilnarang** [comment]
@codebam Lit

**Comment by nicholaschum** [comment]
I approve of this commit

**Pull request closed without merging**
