### PR TITLE
SubstratumRescue: Do not wipe /sdcard/substratum

### PR DESCRIPTION
**Pull request by msfjarvis**
Even though this part of the code https://github.com/substratum/substratum/blob/dev/app/src/main/java/projekt/substratum/common/References.java#L464-L466
should recreate the directory, this is not working out, so weed out
the source of the issue itself.

### CODE REVIEW

**Comment by KreAch3R** [comment]
Show the diff again :) I can't exactly follow. Why is the code not working? And even if it doesn't, we shouldn't rely on the directory just "being" there; we should make sure it can be created correctly.

**Comment by nicholaschum** [comment]
bump

**Comment by minz1** [comment]
@nicholaschum no

**Comment by nicholaschum** [comment]
final bump

**Comment by nicholaschum** [comment]
please add this functionality too while you're at it @MSF-Jarvis:

https://forum.xda-developers.com/showpost.php?p=72585769&postcount=2561

**Comment by msfjarvis** [comment]
@nicholaschum rescue_legacy.dat diff in #107 clearly shows the /data/resource-cache gets wiped in the legacy version of the ZIP. Does the normal OMS variant of the rescue zip have to wipe resource-cache too? I'm still not home for at least two more days so you can probably close this one for the time being and I'll wrap it up when I'm home so we can proceed with merging if necessary

**Pull request merged**
