### PR TITLE
Make Capitalization Great Again

### PR DESCRIPTION
**Pull request by Beanstown**
*the rest of the settings menu has proper capitalisation but the "about section" this triggers alot of people lets fix it :P

### CODE REVIEW

**Comment by AdmireTheDistance** [comment]
+ a billion

**Comment by AdmireTheDistance** [comment]
Stupid markup. Plus a billion

**Comment by Surge1223** [comment]
This is dumber than pure going user build only.

**Comment by BoredOutOfMyGit** [comment]
Beans does have a point if we're going off material design guidelines

https://material.io/guidelines/style/writing.html#writing-capitalization-punctuation

**Comment by AdmireTheDistance** [comment]
Oh, sure, when Beans says it, he has a point. When I mentioned it not following guidelines in chat, I got shut down. Haters.

**Comment by valiantshadow** [comment]
I'm all for capitalization, but this same thing has been done and asked for over and over again, and the team has said no every time, and I doubt that this time would be an exception. However, I don't want to speak for the Substratum team.

**Comment by Beanstown** [comment]
@valiantshadow

**Comment by BoredOutOfMyGit** [comment]
Sorry Ben, I never saw where you mentioned it. I was just talking about it now and I remembered having a similar discussion with one of our guys in DU and so I knew that piece in the guidelines was there.

**Comment by AdmireTheDistance** [comment]
Lol it was a looong time ago in chat Alex. I couldn't care less.

**Comment by Surge1223** [comment]
well my two cents,   i normally wouldn't prefer one or the other, but  since it has no actual meaningful change to the functionality of subs, i guess id just need a better reason to be on board.  we're not cts ready or anything. but please vote amongst yourselves 

p.s. please don't get mad about my lack of capitalization, i was going to, but then i realized it didn't matter.

**Comment by BoredOutOfMyGit** [comment]
@Surge1223 Lol

**Comment by Sykopompos** [comment]
Oh fuck no, now I want to leave it exactly as is because I know how much it triggers now

**Comment by AdmireTheDistance** [comment]
@Sykopompos You suck Mike.

**Comment by Sykopompos** [comment]
@AdmireTheDistance

**Comment by Beanstown** [comment]
@Sykopompos see his is a shitty attitude to have towards a supposed community project

**Comment by Sykopompos** [comment]
@beanstown106 Nope, just trolling when I hear the words this triggers me

**Review by nicholaschum — APPROVED** [review]

**Comment by nicholaschum** [comment]
merged.

**Pull request merged**
