### PR TITLE
Gradle: Remove explicit jar to implement

### PR DESCRIPTION
**Pull request by ghost**
gib pizza 🍕

### CODE REVIEW

**Comment by sokryptk** [comment]
@alamo18 Why such fuckery.

**Comment by argraur** [comment]
@alamo18 I want one 2 pl0x

**Comment by ghost** [comment]
pizza

**Comment by argraur** [comment]
@alamo18 Yummy

**Comment by nicholaschum** [comment]
Build is failing, please fix and recommit

**Comment by Surge1223** [comment]
What is this pizza crap

**Comment by Sykopompos** [comment]
@Surge1223 Pizza pizza 🍕

**Comment by msfjarvis** [comment]
Lame troll

**Pull request closed without merging**
