### PR TITLE
Revert "Revert "debug builds: show git HASH on filename & in Settings""

### PR DESCRIPTION
**Pull request by nathanchance**
@MSF-Jarvis: https://cdn.arstechnica.net/wp-content/uploads/2012/06/torvaldsnvidia-640x424.jpg

This reverts commit 243bee3b97d841805dce251704d379a17ebb51d2.

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

### CODE REVIEW

**Comment by msfjarvis** [comment]
._.

**Comment by msfjarvis** [comment]
1) George wanted it
2) Next time use markdown for pics

**Comment by nathanchance** [comment]
1. Does George even build Subs anymore?
2. It's from git pull-request because it's in the commit message so me no cur

**Comment by ivaniskandar** [comment]
@nathanchance you better mend it mister

**Comment by nathanchance** [comment]
@iskandar1023 

whoops

**Comment by ivaniskandar** [comment]
@nathanchance

**Pull request merged**
