### PR TITLE
Some fixes and updates

### PR DESCRIPTION
**Pull request by sirmordred**

### CODE REVIEW

**Review by ivaniskandar — CHANGES_REQUESTED** [review]
Can you utilize java 8 auto closeable here? I believe some try block can be avoided.

**Comment by sirmordred** [comment]
Done
Also is the "if-else statement" in following patch a really typo(same if-else statements) or was it implemented in this way for other reasons?
https://github.com/substratum/substratum/pull/106/commits/45a86d3b7f9d986b6fc2ebd75e04a64ad3a55242

**Comment by nicholaschum** [comment]
@sirmordred are you on Telegram? If you are, we'd be happy for you to discuss further implementations in our app specific chat 👍 My Telegram is @nicholaschum.

**Comment by sirmordred** [comment]
hi @nicholaschum sorry for the delay, and yep i have it, its better than here :+1: i have sent you a message

**Pull request merged**
