### PR TITLE
Ah, proper capitalization

### PR DESCRIPTION
**Pull request by r-matlock**
- Just give the app proper capitalization and grammar. 
- A masquerade commit will be uploaded soon.

Signed-off-by: Raleigh Matlock raleighman2@gmail.com

### CODE REVIEW

**Comment by nicholaschum** [comment]
@xX-Yoshi-Xx You can keep this on your fork of the project. However this pull request will be closed and unmerged. Sorry.

**Comment by r-matlock** [comment]
@nicholaschum Is there a particular reason for keeping everything in the app lowercase? Just curious.

**Comment by nicholaschum** [comment]
@xX-Yoshi-Xx I prefer the look of lower cased letters. There's a reason that there is perfect English everywhere but capitalization.

**Comment by r-matlock** [comment]
@nicholaschum Ok, gotcha. Thanks

**Pull request closed without merging**
