### PR TITLE
Add legacy font suport

### PR DESCRIPTION
**Pull request by camcory**
Requires frameworks substratum legacy font commit.

https://goo.gl/iqUwPi

### CODE REVIEW

**Comment by nicholaschum** [comment]
Cory, we need a way to check whether a ROM is running with that commit, because this shouldn't be by default working on stock.

**Comment by KreAch3R** [comment]
@nicholaschum Will you work on the reflection idea to check that or is that abandoned?

**Comment by nicholaschum** [comment]
@KreAch3R Not abandoned. I'll merge the pull request as soon as it is ready with the reflection class checker.

**Comment by nicholaschum** [comment]
Let's begin working on this...

**Pull request merged**
