### PR TITLE
SubstratumRescueSystem: Clean theme assets directory as well

### PR DESCRIPTION
**Pull request by msfjarvis**
Previously the rescue zip used to create the theme dir if missing, but this
causes unintended behaviour where themed bootanimations and fonts do not
get removed. Change this up for both legacy and oms to delete the /data/system/theme
directory since they get created by the userspace applications when needed.

interfacer ensures the theme dir is present via this commit
https://github.com/substratum/interfacer/commit/bed5f4407b372fa999df54a18939149b1f029a9c

### CODE REVIEW

**Comment by KreAch3R** [comment]
Please show the changes made inside the .dat file @MSF-Jarvis, I don't want to download both and compare :) 
(Use the git patch format and post it here in code tags)

**Comment by msfjarvis** [comment]
My bad, forgot it.

`rescue.dat` diff

```
diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
index d5e9251..00c9aee 100644
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -24,12 +24,15 @@ ui_print "- Removing Substratum directories"
 rm -rf /sdcard/substratum
 rm -rf /sdcard/.substratum
 
+ui_print "- Removing theme directory"
+rm -rf /data/system/theme
-ui_print "- Setting up theme directory"
-if [ ! -d "/data/system/theme" ]; then
-    ui_print "- Creating folder..." 
-    mkdir /data/system/theme 
-fi
 
+ui_print "- Correcting permissions..."
-ui_print "- Correcting permissions..." 
 chown 1000:1000 /data/system/theme
 chmod 0755 -R /data/system/theme
 
 ui_print "- Unmounting /system"
+umount /system
-umount /system
\ No newline at end of file
```

`rescue_legacy.dat` diff

```
--- a/META-INF/com/google/android/updater-script
+++ b/META-INF/com/google/android/updater-script
@@ -8,7 +8,6 @@ run_program("/sbin/busybox", "mount", "/system");
 run_program("/sbin/busybox", "mount", "/vendor");
 ui_print("     Mounting /vendor and /system partitions...");
 ui_print(" ");
+delete_recursice("/data/system/theme");
 delete_recursive("/data/resource-cache/");
 delete_recursive("/vendor/overlay/");
 delete_recursive("/system/vendor/overlay");
@@ -18,4 +17,4 @@ unmount("/system");
 unmount("/vendor");
 ui_print(" ");
 ui_print("     Unmounting all partitions after flash...");
+ui_print(" ");
-ui_print(" ");
\ No newline at end of file
```

Lines with no apparent changes have had trailing whitespace stripped.

**Comment by KreAch3R** [comment]
Thanks!

There's a typo in that legacy diff, *recursive*, right?

**Comment by msfjarvis** [comment]
Fixed it

**Pull request merged**
